In [1]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [2]:
A=Hut_Paradise_DF.values

In [3]:
print('Appartment 5:', A[4])

Appartment 5: [40 33  1  6 20 16]


In [4]:
print('Floor:',A[:,3])

Floor: [ 5 12 10  3  6 13  8 21  5]


In [5]:
non_live_area = A[:,1]-A[:,5]
non_live_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [6]:
demo = A[:,4]
time = 10*demo[0]+20*demo[1]+30*demo[2]+15*demo[3]+5*demo[4]+40*demo[5]+20*demo[6]+8*demo[7]+20*demo[8]
time

1348

In [7]:
import numpy as np
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [8]:
x = v*2+w*-3
x

array([-3, 14,  3,  4,  2])

In [9]:
print('(u,x):', np.dot(u,x))

(u,x): 0


In [10]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [11]:
data = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
inc = data.T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [12]:
data = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
cons = data.T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [13]:
s = 0.87*inc
s

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [14]:
p = s-cons
p

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [15]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

In [16]:
A@x

array([26, 30])

In [17]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

In [18]:
np.dot(B,A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [19]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A=np.array([x,y,z])
A


array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [20]:
A.T

array([[ 1,  2, -1],
       [ 2,  1,  1],
       [ 1, -1, -1],
       [ 0,  1,  0],
       [ 4,  0,  0]])

In [21]:
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [22]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [23]:
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [24]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
com

array([0.2, 0.2, 0.3, 0.1, 0.1])

In [25]:
income_df = Count_DF*Price_DF
income_df = np.array(income_df)
income_df

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [26]:
income_df@com


array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [27]:
#income_st = np.array([0.8, 0.8, 0.7, 0.9, 0.9])
income_st = np.ones(5)-com
income_st

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [28]:
income_df@income_st

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [29]:
P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [30]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
A

array([[ 8,  6, 11],
       [ 7,  5,  9],
       [ 6, 10,  6]])

In [31]:
A_inv = np.linalg.inv(A)
A_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [32]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [33]:
A=np.array([v1,v2,v3,v4]).T
A

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [34]:
print(np.linalg.matrix_rank(A))

4


In [35]:
gr=A.T@A
gr

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [36]:
opr = round(np.linalg.det(gr))
opr

3716648

In [37]:
gr_inv = np.linalg.inv(gr)
gr_inv

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [38]:
v_1 = np.array([5,1,2])
u_1 = np.array([4,2,8])
print(np.corrcoef(v_1, u_1))

[[1.         0.05241424]
 [0.05241424 1.        ]]


In [39]:
x_1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x_2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x_3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
A = np.corrcoef([x_1, x_2, x_3])

In [40]:
np.linalg.matrix_rank(A)

3

In [41]:
print('Determinant: {:.7f}'.format(np.linalg.det(A)))

Determinant: 0.0000005


In [42]:
np.linalg.det(A)

4.862298229241645e-07

In [43]:
print(A)

[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]


MATH_ML_2

In [44]:
A = np.array([[1,1,1,1],
              [1,3,-2,9],
              [1,9,4,81]
              ]).T
y = np.array([3,7,-5,21])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat)


[ 0.11446013  2.46095638 -0.01608801]


In [45]:
A = np.array([
    [1,1,1,1,1],
    [5,9,4,3,5],
    [15,18,18,19,19],
    [7,6,7,7,7]
]).T
y = np.array([24,22,35,33,36])
E = np.eye(4)
alpha = 1
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(np.around(w_hat_ridge, decimals=2))

[-0.09 -1.71  1.91  0.73]


MATH_ML_3

In [50]:
A = np.array([
    [1,4,13],
    [3,-4,7],
    [5,9,12]
])
eig_values, eig_vectors = np.linalg.eig(A)
print(eig_values)

[19.52189628 -3.75422737 -6.76766891]


In [51]:
A = np.array([
    [1,9,4],
    [9,4,7],
    [4,7,12]
])
X = A.T@A
eig_values, eig_vectors = np.linalg.eig(X)
print(eig_values)

[391.37004987  45.77088847  15.85906166]


In [52]:

x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([[1, 0.9922], [0.9922, 1]])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

[-0.24  0.86 -0.29 -0.33]
